# Generated by Django 3.0.2 on 2020-04-10 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('khodi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khodi',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khodi',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 19, 57, 25, 111567, tzinfo=utc)),
        ),
    ]
